//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sales
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public Nullable<int> ConsultantID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public string SaleDescription { get; set; }
    
        public virtual Consultants Consultants { get; set; }
        public virtual Products Products { get; set; }
    }
}
